--- #YAML:1.0
name:               EJS-Template
version:            0.01
abstract:           EJS (Embedded JavaScript) template engine
author:
    - Mahiro Ando <mahiro@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Scalar:   0
    JE:           0
    Test::More:   0
    URI::Escape:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
